name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 16 2019" -A x64 -DBUILD_TESTING=OFF -DLIBSAMPLERATE_EXAMPLES=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"

    - name: Build Release
      run: cmake --build build --config Release

    - name: Build Debug
      run: cmake --build build --config Debug

    - name: Pack NuGet
      run: nuget pack shapedbyiris.libsamplerate.nuspec -p version=$((Get-Date).tostring("yyyy.MMdd.HHmm"))

    - name: Publish NuGet
      if: github.event_name != 'pull_request'
      run: |
        nuget sources Add -Name github -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -Username ${{github.repository_owner}} -Password ${{github.token}}
        nuget push *.nupkg -Source github -SkipDuplicate -ApiKey ${{github.token}}
